#!/usr/bin/env zsh

# Help

# b   = bold
# i   = underline
# bg  = background
# c   = contrast (High Intensity)
# bc  = bold contrast
# cbg = contrast background

# Regular Colors

Black=$'\e[0;30m'
Red=$'\e[0;31m'
Green=$'\e[0;32m'
Yellow=$'\e[0;33m'
Blue=$'\e[0;34m'
Purple=$'\e[0;35m'
Cyan=$'\e[0;36m'
White=$'\e[0;37m'

# Bold

bBlack=$'\e[1;30m'
bRed=$'\e[1;31m'
bGreen=$'\e[1;32m'
bYellow=$'\e[1;33m'
bBlue=$'\e[1;34m'
bPurple=$'\e[1;35m'
bCyan=$'\e[1;36m'
bWhite=$'\e[1;37m'

# Underline

iBlack=$'\e[4;30m'
iRed=$'\e[4;31m'
iGreen=$'\e[4;32m'
iYellow=$'\e[4;33m'
iBlue=$'\e[4;34m'
iPurple=$'\e[4;35m'
iCyan=$'\e[4;36m'
iWhite=$'\e[4;37m'

# Background

bgBlack=$'\e[40m'
bgRed=$'\e[41m'
bgGreen=$'\e[42m'
bgYellow=$'\e[43m'
bgBlue=$'\e[44m'
bgPurple=$'\e[45m'
bgCyan=$'\e[46m'
bgWhite=$'\e[47m'

# High Intensity

cBlack=$'\e[0;90m'
cRed=$'\e[0;91m'
cGreen=$'\e[0;92m'
cYellow=$'\e[0;93m'
cBlue=$'\e[0;94m'
cPurple=$'\e[0;95m'
cCyan=$'\e[0;96m'
cWhite=$'\e[0;97m'

# Bold High Intensity

bcBlack=$'\e[1;90m'
bcRed=$'\e[1;91m'
bcGreen=$'\e[1;92m'
bcYellow=$'\e[1;93m'
bcBlue=$'\e[1;94m'
bcPurple=$'\e[1;95m'
bcCyan=$'\e[1;96m'
bcWhite=$'\e[1;97m'

# High Intensity Backgrounds

cbgBlack=$'\e[0;100m'
cbgRed=$'\e[0;101m'
cbgGreen=$'\e[0;102m'
cbgYellow=$'\e[0;103m'
cbgBlue=$'\e[0;104m'
cbgPurple=$'\e[0;105m'
cbgCyan=$'\e[0;106m'
cbgWhite=$'\e[0;107m'

# Reset
Reset=$'\e[0m'

